export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { EdgeStoreProvider } from '../../lib/edgestore'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <EdgeStoreProvider>
          {children}
        </EdgeStoreProvider>
      </body>
    </html> 
  )
}
