import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import MenuDisplay from '../../components/userComponents/primaryComponents/menuComponents/menuDisplay'
import Footer from '../../components/userComponents/primaryComponents/footerComponents/footer'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuDisplay/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
