require("dotenv").config();

import { EdgeStoreProvider } from '../lib/edgestore';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ContextState from '../../components/systemComponents/context/contextStates';
import Provider from './sessionProvider';

import mongoose from "mongoose";

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  try {
    if (process.env.MONGO_URI) {
      await mongoose.connect(process.env.MONGO_URI);
      return (
        <html lang="en">
          <body className={inter.className}>
            <Provider>
              <EdgeStoreProvider>
                <ContextState>
                  {children}
                </ContextState>
              </EdgeStoreProvider>
            </Provider>
          </body>
        </html>
      )
    }
    else return <h5> Mongo URI missing </h5>

  }
  catch (err) {
    return <h5> Error connecting to the database </h5>
  }
}
